name: shadow_sso_client
description: "Shadow SSO client for Flutter"
version: 0.0.1
homepage: https://pilab.hu/projects/shadow-sso
repository: https://gitlab.com/pilab-dev/shadow-sso-client

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
